micronaut:
  application:
    name: MicronautApp
  server:
    port: 8080
    thread-selection: IO
  metrics:
    enabled: true
    # export:
    #   prometheus:
    #     enabled: true
    #     step: PT1M
    #     descriptions: true

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    dialect: POSTGRES
    url: ${JDBC_URL:`jdbc:postgresql://postgres-ha:5432/postgres`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:password}
    driverClassName: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      packages: 'io.containerapps.javaruntime.workshop.micronaut'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
        show_sql: false

endpoints:
  prometheus:
    sensitive: false