version: '3'
volumes:
  postgresql_data:
    driver: local
services:
  postgres:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - .initdb/:/docker-entrypoint-initdb.d:ro
    environment:
      # - 'ALLOW_EMPTY_PASSWORD=yes'
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_POSTGRES_PASSWORD=password
      - POSTGRESQL_DATABASE=postgres
  quarkus-app:
    image: quay.io/rafaeltuelho/quarkus-app:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [ postgres ]
    ports:
    - 8701:8080
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - QUARKUS_LOG_CATEGORY__ORG_HIBERNATE__LEVEL=INFO
  micronaut-app:
    image: quay.io/rafaeltuelho/micronaut-app:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [ postgres ]
    ports:
    - 8702:8080
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/postgres
  springboot-app:
    image: quay.io/rafaeltuelho/springboot-app:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [ postgres ]
    ports:
    - 8703:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - spring_profiles_active=production